version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "15678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=151515Rog98**!
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost/
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/home/node/.n8n
